Another version of text_classifier_pytorch.ipynb, where pytorch version same as on google cloud 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%pwd

'/content/drive/MyDrive/Github/ml_dl_tweets_sentiment'

In [ ]:
%cd drive/MyDrive/Github/ml_dl_tweets_sentiment

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment


In [ ]:
!git config --global user.email "email@gmail.com" 
!git config --global user.name "Putilova"

In [ ]:
# When GitHub files aren't in local Drive
!git pull

remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/Putilova/ml_dl_tweets_sentiment
   60064dc..07b9022  main       -> origin/main
hint: Waiting for your editor to close the file... error: unable to start editor 'editor'
Not committing merge; use 'git commit' to complete the merge.


In [ ]:
!pip install torch==1.0.1 torchvision==0.2.2

     |████████████████████████████████| 560.1 MB 20 kB/s 
     |████████████████████████████████| 64 kB 2.6 MB/s 
     |████████████████████████████████| 52 kB 1.1 MB/s 
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.63.0
    Uninstalling tqdm-4.63.0:
      Successfully uninstalled tqdm-4.63.0
  Attempting uninstall: torch
    Found existing installation: torch 1.10.0+cu111
    Uninstalling torch-1.10.0+cu111:
      Successfully uninstalled torch-1.10.0+cu111
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.11.1+cu111
    Uninstalling torchvision-0.11.1+cu111:
      Successfully uninstalled torchvision-0.11.1+cu111
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchtext 0.11.0 requires torch==1.10.0, but you have torch 1.0.1 which is incompatible.
torchaudio 0.10.0+cu111 requires torch==1.10.0, but you h

In [ ]:
import nltk

In [ ]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloadin

True

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('../_06_28_text_classifier/Restaurant_Reviews.tsv.txt', delimiter= '\t', quoting = 3)

In [ ]:
dataset.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [ ]:
from nltk.corpus import stopwords


In [ ]:
from nltk.stem.porter import PorterStemmer


In [ ]:
ps = PorterStemmer()


In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [ ]:
corpus = []


In [ ]:
import re

In [ ]:
for i in range(0, 1000):

  customer_review = re.sub('[^a-zA-Z]', ' ',dataset['Review'][i])
  customer_review = customer_review.lower()
  customer_review = customer_review.split()
  clean_review = [ps.stem(word) for word in customer_review if not word in set(stopwords.words('english'))]
  clean_review = ' '.join(clean_review)
  corpus.append(clean_review)

In [ ]:
corpus[0]

'wow love place'

In [ ]:
corpus[6]

'honeslti tast fresh'

In [ ]:
corpus[12]

'cashier care ever say still end wayyy overpr'

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features = 1500, min_df = 3, max_df = 0.6)


In [ ]:
X = vectorizer.fit_transform(corpus).toarray()


In [ ]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [ ]:
y = dataset.iloc[:, 1].values

In [ ]:
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [ ]:
print(torch.__version__)

1.0.1


In [ ]:
Xtrain_ = torch.from_numpy(X_train).float()
Xtest_ = torch.from_numpy(X_test).float()

In [ ]:
ytrain_ = torch.from_numpy(y_train)
ytest_ = torch.from_numpy(y_test)

In [ ]:
Xtrain_.shape, ytrain_.shape

(torch.Size([800, 467]), torch.Size([800]))

In [ ]:
Xtest_.shape, ytest_.shape

(torch.Size([200, 467]), torch.Size([200]))

In [ ]:
input_size=467
output_size=2
hidden_size=500

In [ ]:
class Net(nn.Module):
   def __init__(self):
       super(Net, self).__init__()
       self.fc1 = torch.nn.Linear(input_size, hidden_size)
       self.fc2 = torch.nn.Linear(hidden_size, hidden_size)
       self.fc3 = torch.nn.Linear(hidden_size, output_size)


   def forward(self, X):
       X = torch.relu((self.fc1(X)))
       X = torch.relu((self.fc2(X)))
       X = self.fc3(X)

       return F.log_softmax(X,dim=1)

In [ ]:
model = Net()


In [ ]:
import torch.optim as optim
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.NLLLoss()

In [ ]:
epochs = 100


In [ ]:
for epoch in range(epochs):
  optimizer.zero_grad()
  Ypred = model(Xtrain_)
  loss = loss_fn(Ypred,  ytrain_)
  loss.backward()
  optimizer.step()
  print('Epoch',epoch, 'loss',loss.item())

Epoch 0 loss 0.6931198835372925
Epoch 1 loss 0.6691915392875671
Epoch 2 loss 0.5269927978515625
Epoch 3 loss 0.34747302532196045
Epoch 4 loss 0.20839424431324005
Epoch 5 loss 0.1380375325679779
Epoch 6 loss 0.10257747024297714
Epoch 7 loss 0.08868294954299927
Epoch 8 loss 0.06432180851697922
Epoch 9 loss 0.04941769689321518
Epoch 10 loss 0.047446902841329575
Epoch 11 loss 0.04781627655029297
Epoch 12 loss 0.03639417886734009
Epoch 13 loss 0.035636577755212784
Epoch 14 loss 0.03902702033519745
Epoch 15 loss 0.03772862255573273
Epoch 16 loss 0.031948428601026535
Epoch 17 loss 0.034304216504096985
Epoch 18 loss 0.03297891840338707
Epoch 19 loss 0.031776949763298035
Epoch 20 loss 0.03168987110257149
Epoch 21 loss 0.03068399243056774
Epoch 22 loss 0.03142083063721657
Epoch 23 loss 0.030573148280382156
Epoch 24 loss 0.030417315661907196
Epoch 25 loss 0.02933165617287159
Epoch 26 loss 0.029978584498167038
Epoch 27 loss 0.029863255098462105
Epoch 28 loss 0.029153158888220787
Epoch 29 loss 0.03

In [ ]:
sample = ["Good batting by England"]


In [ ]:
sample = vectorizer.transform(sample).toarray()


In [ ]:
sample

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [ ]:
torch.from_numpy(sample).float()

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.,

In [ ]:
sentiment = model(torch.from_numpy(sample).float())
sentiment

tensor([[-1.9164, -0.1591]], grad_fn=<LogSoftmaxBackward>)

In [ ]:
sample2 = ["bad performance by India in the match"]


In [ ]:
sample2 = vectorizer.transform(sample2).toarray()


In [ ]:
sentiment2 = model(torch.from_numpy(sample2).float())
sentiment2

tensor([[  0.0000, -49.2863]], grad_fn=<LogSoftmaxBackward>)

In [ ]:
model.state_dict()

OrderedDict([('fc1.weight',
              tensor([[-5.6044e-02, -5.1322e-02, -1.4304e-01,  ...,  6.3430e-02,
                        1.6764e-02, -1.0689e-01],
                      [ 4.8590e-02,  1.2543e-01, -5.2354e-02,  ..., -4.9480e-02,
                       -8.3571e-03,  8.7571e-02],
                      [ 9.9942e-02,  1.1088e-01, -1.2948e-02,  ..., -5.7231e-02,
                       -6.7249e-02,  1.4841e-01],
                      ...,
                      [-1.4915e-02, -2.5362e-02,  4.4633e-02,  ..., -4.6843e-03,
                        9.3006e-05, -4.4792e-02],
                      [ 1.8220e-01, -3.5220e-02, -7.5375e-02,  ..., -2.4965e-02,
                       -2.1604e-02, -2.6428e-02],
                      [-7.9684e-02,  7.2600e-03, -9.0000e-02,  ...,  8.9195e-02,
                        4.5977e-02, -1.0179e-01]])),
             ('fc1.bias',
              tensor([ 0.0110,  0.0491, -0.0390,  0.0528, -0.0951,  0.0150, -0.0066,  0.0300,
                      -0.0103,  0.01

In [ ]:
torch.save(model.state_dict(),'text_classifier_pytorch_1')

In [ ]:
#!ls

In [ ]:
#from google.colab import files

In [ ]:
#files.download('text_classifier_pytorch')

In [ ]:
import pickle

In [ ]:
with open('tfidfmodel.pickle','wb') as file:
    pickle.dump(vectorizer,file)

In [ ]:
#files.download('tfidfmodel.pickle')

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   text_classifier_pytorch.ipynb
	modified:   tf_nlp_rest.ipynb
	modified:   tfidfmodel.pickle

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	text_classifier_pytorch_1

no changes added to commit (use "git add" and/or "git commit -a")


In [ ]:
# Add local Drive files to GitHub
!git add .

In [ ]:
# Add comment and send added files to GitHub
!git commit -m "Created PyTorch model"

[main cf54d44] Created PyTorch model
 1 file changed, 1 insertion(+)
 create mode 100644 text_classifier_pytorch_101.ipynb


In [ ]:
# Send to main
!git push

To https://github.com/Putilova/ml_dl_tweets_sentiment
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://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@github.com/Putilova/ml_dl_tweets_sentiment'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
