In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%pwd

'/content'

In [ ]:
%cd drive/MyDrive/Github/ml_dl_tweets_sentiment

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment


In [ ]:
%cd _03_10_use_model_colab

In [ ]:
import numpy as np
import pickle

In [ ]:
#!wget https://github.com/futurexskill/ml-model-deployment/raw/main/classifier.pickle
#!wget https://github.com/Putilova/ml_dl_tweets_sentiment/raw/main/classifier.pickle

In [ ]:
#!wget https://github.com/futurexskill/ml-model-deployment/raw/main/sc.pickle
#!wget https://github.com/Putilova/ml_dl_tweets_sentiment/raw/main/sc.pickle

In [ ]:
classifier_colab = pickle.load(open('../_02_07_ml_classification/classifier.pickle','rb'))


In [ ]:
scaler_colab = pickle.load(open('../_02_07_ml_classification/sc.pickle','rb'))

In [ ]:
new_pred = classifier_colab.predict(scaler_colab.transform(np.array([[40,20000]])))


In [ ]:
new_pred

array([0])

In [ ]:
new_pred_proba = classifier_colab.predict_proba(scaler_colab.transform(np.array([[40,20000]])))[:,1]
new_pred_proba


array([0.2])

In [ ]:
new_pred_2 = classifier_colab.predict(scaler_colab.transform(np.array([[42,50000]])))
new_pred_proba_2 = classifier_colab.predict_proba(scaler_colab.transform(np.array([[42,50000]])))[:,1]
new_pred_2

array([1])

In [ ]:
new_pred_proba_2

array([0.8])