In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%pwd

'/content'

In [ ]:
%cd drive/MyDrive/Github/ml_dl_tweets_sentiment

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment


In [ ]:
!git config --global user.email "email@gmail.com" 
!git config --global user.name "Putilova"

In [ ]:
# When GitHub files aren't in local Drive
!git pull

Already up to date.


In [ ]:
!ls

classifier.pickle		  text_classifier_pytorch
ml_pipeline.ipynb		  text_classifier_pytorch_1
pytorch_nlp_rest.ipynb		  text_classifier_pytorch_101.ipynb
pytorch_serverless_main_w_exc.py  text_classifier_pytorch.ipynb
README.md			  text_classifier_tensorflow.ipynb
Restaurant_Reviews.tsv.txt	  tfidfmodel.pickle
sc.pickle			  tf_nlp_rest.ipynb
storepurchasedata.csv		  tfserverless_main_w_exc.py
text_classifier.ipynb		  twitter_sentiment_analysis.ipynb
text_classifier_model		  twitter_sentiment_analysis_output_log.txt
text_classifier_model.zip	  use_model_colab.ipynb
textclassifier.pickle


In [ ]:
%cd _03_10_use_model_colab

In [ ]:
import numpy as np
import pickle

In [ ]:
#!wget https://github.com/futurexskill/ml-model-deployment/raw/main/classifier.pickle
#!wget https://github.com/Putilova/ml_dl_tweets_sentiment/raw/main/classifier.pickle

In [ ]:
#!wget https://github.com/futurexskill/ml-model-deployment/raw/main/sc.pickle
#!wget https://github.com/Putilova/ml_dl_tweets_sentiment/raw/main/sc.pickle

In [ ]:
classifier_colab = pickle.load(open('../_02_07_ml_classification/classifier.pickle','rb'))


In [ ]:
scaler_colab = pickle.load(open('../_02_07_ml_classification/sc.pickle','rb'))

In [ ]:
new_pred = classifier_colab.predict(scaler_colab.transform(np.array([[40,20000]])))


In [ ]:
new_pred

array([0])

In [ ]:
new_pred_proba = classifier_colab.predict_proba(scaler_colab.transform(np.array([[40,20000]])))[:,1]
new_pred_proba


array([0.2])

In [ ]:
new_pred_2 = classifier_colab.predict(scaler_colab.transform(np.array([[42,50000]])))
new_pred_proba_2 = classifier_colab.predict_proba(scaler_colab.transform(np.array([[42,50000]])))[:,1]
new_pred_2

array([1])

In [ ]:
new_pred_proba_2

array([0.8])

In [ ]:
%cd ..

'/content/drive/MyDrive/Github/ml_dl_tweets_sentiment'

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ml_pipeline.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	use_model_colab.ipynb

no changes added to commit (use "git add" and/or "git commit -a")


In [ ]:
# Add local Drive files to GitHub
!git add .

In [ ]:
# Add comment and send added files to GitHub
!git commit -m "Modified files"

On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
	modified:   use_model_colab.ipynb

no changes added to commit


In [ ]:
# Send to main
!git push

Counting objects: 4, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 3.45 KiB | 393.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 2 local objects.
To https://github.com/Putilova/ml_dl_tweets_sentiment.git
   abdd9c9..9d37bdd  main -> main


In [ ]:
# On git push failure:
git_token = 'token'
username = 'Putilova'
repository = 'ml_dl_tweets_sentiment'
!git remote set-url origin https://{username}:{git_token}@github.com/{username}/{repository}.git