In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%pwd

'/content'

In [ ]:
%cd drive/MyDrive/Github/ml_dl_tweets_sentiment

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment


In [ ]:
!git config --global user.email "email@gmail.com" 
!git config --global user.name "Putilova"

In [ ]:
# When GitHub files aren't in local Drive
!git pull

Already up to date.


In [ ]:
!ls

classifier.pickle		  text_classifier_model.zip
colab_rest_api_pyngrok.ipynb	  textclassifier.pickle
customer_buy.pt			  text_classifier_pytorch
customer_buy_state_dict		  text_classifier_pytorch_1
customer_buy_state_dict.zip	  text_classifier_pytorch_101.ipynb
ml_pipeline.ipynb		  text_classifier_pytorch.ipynb
pytorch_nlp_rest.ipynb		  text_classifier_tensorflow.ipynb
pytorch_serverless_main_w_exc.py  tf_customer_buy.ipynb
README.md			  tfidfmodel.pickle
Restaurant_Reviews.tsv.txt	  tf_nlp_rest.ipynb
sc.pickle			  tfserverless_main_w_exc.py
storepurchasedata.csv		  twitter_sentiment_analysis.ipynb
storepurchasedata_large.csv	  twitter_sentiment_analysis_output_log.txt
text_classifier.ipynb		  use_model_colab.ipynb
text_classifier_model		  use_pytorch_dictionary.ipynb


In [ ]:
%cd _05_22_tf_serving_save_export

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
#dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/storepurchasedata_large.csv')
dataset = pd.read_csv('../_05_20_save_export_reload_pytorch_models/storepurchasedata_large.csv')

In [ ]:
dataset.describe()

Age        Salary    Purchased
count  1554.000000   1554.000000  1554.000000
mean     44.296010  57042.471042     0.694981
std      17.462458  21209.244800     0.460564
min      18.000000  20000.000000     0.000000
25%      27.000000  46000.000000     0.000000
50%      43.000000  60000.000000     1.000000
75%      62.000000  66000.000000     1.000000
max      69.000000  96000.000000     1.000000

In [ ]:
dataset.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   60000          1

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(2, activation='softmax')
])

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=50)


Epoch 1/50
39/39 [==============================] - 1s 2ms/step - loss: 0.5857 - accuracy: 0.6975
Epoch 2/50
39/39 [==============================] - 0s 2ms/step - loss: 0.4868 - accuracy: 0.6991
Epoch 3/50
39/39 [==============================] - 0s 2ms/step - loss: 0.4251 - accuracy: 0.6991
Epoch 4/50
39/39 [==============================] - 0s 2ms/step - loss: 0.3780 - accuracy: 0.7659
Epoch 5/50
39/39 [==============================] - 0s 2ms/step - loss: 0.3363 - accuracy: 0.8729
Epoch 6/50
39/39 [==============================] - 0s 2ms/step - loss: 0.2936 - accuracy: 0.9308
Epoch 7/50
39/39 [==============================] - 0s 2ms/step - loss: 0.2513 - accuracy: 0.9533
Epoch 8/50
39/39 [==============================] - 0s 2ms/step - loss: 0.2116 - accuracy: 0.9606
Epoch 9/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1814 - accuracy: 0.9558
Epoch 10/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1588 - accuracy: 0.9566
Epoch 11/50
39/39 [

In [ ]:
loss, accuracy =model.evaluate(X_test, y_test)


10/10 [==============================] - 0s 2ms/step - loss: 0.1059 - accuracy: 0.9550


In [ ]:
loss

0.10593230277299881

In [ ]:
accuracy

0.9549839496612549

In [ ]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 2)                 22        
                                                                 
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [ ]:
prediction1 = model.predict(sc.transform(np.array([[42,50000]])))[:,1]
prediction1

array([0.6652777], dtype=float32)

In [ ]:
predict2 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict2

array([0.00715642], dtype=float32)

In [ ]:
model.save('customer_behavior_model/1')


INFO:tensorflow:Assets written to: customer_behavior_model/1/assets


In [ ]:
!ls

classifier.pickle		  text_classifier_model.zip
colab_rest_api_pyngrok.ipynb	  textclassifier.pickle
customer_behavior_model		  text_classifier_pytorch
customer_buy.pt			  text_classifier_pytorch_1
customer_buy_state_dict		  text_classifier_pytorch_101.ipynb
customer_buy_state_dict.zip	  text_classifier_pytorch.ipynb
ml_pipeline.ipynb		  text_classifier_tensorflow.ipynb
pytorch_nlp_rest.ipynb		  tf_customer_buy.ipynb
pytorch_serverless_main_w_exc.py  tfidfmodel.pickle
README.md			  tf_nlp_rest.ipynb
Restaurant_Reviews.tsv.txt	  tfserverless_main_w_exc.py
sc.pickle			  twitter_sentiment_analysis.ipynb
storepurchasedata.csv		  twitter_sentiment_analysis_output_log.txt
storepurchasedata_large.csv	  use_model_colab.ipynb
text_classifier.ipynb		  use_pytorch_dictionary.ipynb
text_classifier_model


In [ ]:
!ls customer_behavior_model  

1


In [ ]:
!ls customer_behavior_model/1

assets	keras_metadata.pb  saved_model.pb  variables


In [ ]:
from tensorflow.keras.models import load_model


In [ ]:
cust_model = load_model('customer_behavior_model/1/')

In [ ]:
 prediction3 = cust_model.predict(sc.transform(np.array([[42,50000]])))[:,1]
 prediction3

array([0.6652777], dtype=float32)

In [ ]:
predict4 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict4

array([0.00715642], dtype=float32)

In [ ]:
from tensorflow.keras.models import load_model


In [ ]:
cust_model = load_model('customer_behavior_model/1/')

In [ ]:
 prediction3 = cust_model.predict(sc.transform(np.array([[42,50000]])))[:,1]
 prediction3

array([0.6652777], dtype=float32)

In [ ]:
predict4 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict4

array([0.00715642], dtype=float32)

In [ ]:
!zip -r customermodel.zip customer_behavior_model  

  adding: customer_behavior_model/ (stored 0%)
  adding: customer_behavior_model/1/ (stored 0%)
  adding: customer_behavior_model/1/variables/ (stored 0%)
  adding: customer_behavior_model/1/variables/variables.data-00000-of-00001 (deflated 60%)
  adding: customer_behavior_model/1/variables/variables.index (deflated 64%)
  adding: customer_behavior_model/1/assets/ (stored 0%)
  adding: customer_behavior_model/1/saved_model.pb (deflated 88%)
  adding: customer_behavior_model/1/keras_metadata.pb (deflated 86%)


In [ ]:
#from google.colab import files

In [ ]:
#!ls

In [ ]:
#files.download('customermodel.zip')

In [ ]:
%cd ..

'/content/drive/MyDrive/Github/ml_dl_tweets_sentiment'

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	customer_behavior_model/
	customermodel.zip
	tf_customer_buy.ipynb
	use_pytorch_dictionary.ipynb

nothing added to commit but untracked files present (use "git add" to track)


In [ ]:
# Add local Drive files to GitHub
!git add .

In [ ]:
# Add comment and send added files to GitHub
!git commit -m "Modified files"

[main e975aaa] Modified files
 7 files changed, 9 insertions(+)
 create mode 100644 customer_behavior_model/1/keras_metadata.pb
 create mode 100644 customer_behavior_model/1/saved_model.pb
 create mode 100644 customer_behavior_model/1/variables/variables.data-00000-of-00001
 create mode 100644 customer_behavior_model/1/variables/variables.index
 create mode 100644 customermodel.zip
 create mode 100644 tf_customer_buy.ipynb
 create mode 100644 use_pytorch_dictionary.ipynb


In [ ]:
# Send to main
!git push

Counting objects: 12, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (11/11), done.
Writing objects: 100% (12/12), 39.17 KiB | 2.06 MiB/s, done.
Total 12 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 1 local object.
To https://github.com/Putilova/ml_dl_tweets_sentiment.git
   42c3c0f..e975aaa  main -> main


In [ ]:
# On git push failure:
git_token = 'token'
username = 'Putilova'
repository = 'ml_dl_tweets_sentiment'
!git remote set-url origin https://{username}:{git_token}@github.com/{username}/{repository}.git