In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%pwd

'/content'

In [ ]:
%cd drive/MyDrive/Github/ml_dl_tweets_sentiment

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment


In [ ]:
!git config --global user.email "email@gmail.com" 
!git config --global user.name "Putilova"

In [ ]:
# When GitHub files aren't in local Drive
!git pull

Already up to date.


In [ ]:
!ls

classifier.pickle		  text_classifier_model.zip
colab_rest_api_pyngrok.ipynb	  textclassifier.pickle
customer_behavior_model		  text_classifier_pytorch
customer_buy.pt			  text_classifier_pytorch_1
customer_buy_state_dict		  text_classifier_pytorch_101.ipynb
customer_buy_state_dict.zip	  text_classifier_pytorch.ipynb
customermodel.zip		  text_classifier_tensorflow.ipynb
ml_pipeline.ipynb		  tf_customer_buy.ipynb
pytorch_nlp_rest.ipynb		  tfidfmodel.pickle
pytorch_serverless_main_w_exc.py  tf_nlp_rest.ipynb
README.md			  tfserverless_main_w_exc.py
Restaurant_Reviews.tsv.txt	  twitter_sentiment_analysis.ipynb
sc.pickle			  twitter_sentiment_analysis_output_log.txt
storepurchasedata.csv		  use_model_colab.ipynb
storepurchasedata_large.csv	  use_pytorch_dictionary.ipynb
text_classifier.ipynb		  use_tf_model_serving.ipynb
text_classifier_model


In [ ]:
%cd _05_24_tf_model_serving

In [ ]:
import json
import requests

In [ ]:
import numpy as np

In [ ]:
#!wget https://github.com/futurexskill/ml-model-deployment/raw/main/sc.pickle

In [ ]:
import pickle


In [ ]:
scaler_colab = pickle.load(open('../_02_07_ml_classification/sc.pickle','rb'))

In [ ]:
scaler_colab.transform(np.array([[20,40000]]))

array([[-1.43318661, -0.47466685]])

In [ ]:
scaler_colab.transform(np.array([[42,50000]]))

array([[0.23452145, 0.03675871]])

In [ ]:
url = 'http://34.125.181.30:8501/v1/models/customer_behavior_model:predict'

In [ ]:
request_data = json.dumps({"signature_name": "serving_default",
                   "instances": [[-1.43318661, -0.47466685],[0.2345214460208433, 0.03675871227617118]]
})

In [ ]:
json_response = requests.post(url,request_data)

In [ ]:
print (json_response.text)


{
    "predictions": [[0.959773362, 0.0402267165], [0.000309662893, 0.999690413]
    ]
}


In [ ]:
scaler_colab.transform(np.array([[25,39000]]))

array([[-1.05416206, -0.52580941]])

In [ ]:
scaler_colab.transform(np.array([[40,45000]]))

array([[ 0.08291162, -0.21895407]])

In [ ]:
request_data = json.dumps({"signature_name": "serving_default",
                   "instances": [[-1.05416206, -0.52580941],[ 0.08291162, -0.21895407]]
})

In [ ]:
json_response = requests.post(url,request_data)

In [ ]:
print (json_response.text)


{
    "predictions": [[0.959339, 0.0406610072], [0.00673103658, 0.993268907]
    ]
}


In [ ]:
%cd ..

'/content/drive/MyDrive/Github/ml_dl_tweets_sentiment'

In [ ]:
!git status

On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   use_tf_model_serving.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	pytorch_create_save_onnx.ipynb

no changes added to commit (use "git add" and/or "git commit -a")


In [ ]:
# Add local Drive files to GitHub
!git add .

In [ ]:
# Add comment and send added files to GitHub
!git commit -m "Modified files"

[main ab2ab8d] Modified files
 2 files changed, 2 insertions(+), 1 deletion(-)
 create mode 100644 pytorch_create_save_onnx.ipynb
 rewrite use_tf_model_serving.ipynb (90%)


In [ ]:
# Send to main
!git push

Counting objects: 8, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 11.27 KiB | 1.02 MiB/s, done.
Total 8 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 2 local objects.
To https://github.com/Putilova/ml_dl_tweets_sentiment.git
   e975aaa..ab2ab8d  main -> main


In [ ]:
# On git push failure:
git_token = 'token'
username = 'Putilova'
repository = 'ml_dl_tweets_sentiment'
!git remote set-url origin https://{username}:{git_token}@github.com/{username}/{repository}.git