In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%pwd

'/content'

In [ ]:
%cd drive/MyDrive/Github/ml_dl_tweets_sentiment

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment


In [ ]:
%cd _05_24_tf_model_serving

In [ ]:
import json
import requests

In [ ]:
import numpy as np

In [ ]:
#!wget https://github.com/futurexskill/ml-model-deployment/raw/main/sc.pickle

In [ ]:
import pickle


In [ ]:
scaler_colab = pickle.load(open('../_02_07_ml_classification/sc.pickle','rb'))

In [ ]:
scaler_colab.transform(np.array([[20,40000]]))

array([[-1.43318661, -0.47466685]])

In [ ]:
scaler_colab.transform(np.array([[42,50000]]))

array([[0.23452145, 0.03675871]])

In [ ]:
url = 'http://34.125.181.30:8501/v1/models/customer_behavior_model:predict'

In [ ]:
request_data = json.dumps({"signature_name": "serving_default",
                   "instances": [[-1.43318661, -0.47466685],[0.2345214460208433, 0.03675871227617118]]
})

In [ ]:
json_response = requests.post(url,request_data)

In [ ]:
print (json_response.text)


{
    "predictions": [[0.959773362, 0.0402267165], [0.000309662893, 0.999690413]
    ]
}


In [ ]:
scaler_colab.transform(np.array([[25,39000]]))

array([[-1.05416206, -0.52580941]])

In [ ]:
scaler_colab.transform(np.array([[40,45000]]))

array([[ 0.08291162, -0.21895407]])

In [ ]:
request_data = json.dumps({"signature_name": "serving_default",
                   "instances": [[-1.05416206, -0.52580941],[ 0.08291162, -0.21895407]]
})

In [ ]:
json_response = requests.post(url,request_data)

In [ ]:
print (json_response.text)


{
    "predictions": [[0.959339, 0.0406610072], [0.00673103658, 0.993268907]
    ]
}
