In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%pwd

'/content'

In [ ]:
%cd drive/MyDrive/Github/ml_dl_tweets_sentiment

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment


In [ ]:
!git config --global user.email "email@gmail.com" 
!git config --global user.name "Putilova"

In [ ]:
# When GitHub files aren't in local Drive
!git pull

Already up to date.


In [ ]:
!ls

classifier.pickle		  text_classifier_model
colab_rest_api_pyngrok.ipynb	  text_classifier_model.zip
customer_behavior_model		  textclassifier.pickle
customer_buy.pt			  text_classifier_pytorch
customer_buy_state_dict		  text_classifier_pytorch_1
customer_buy_state_dict.zip	  text_classifier_pytorch_101.ipynb
customermodel.zip		  text_classifier_pytorch.ipynb
ml_pipeline.ipynb		  text_classifier_tensorflow.ipynb
pytorch_create_save_onnx.ipynb	  tf_customer_buy.ipynb
pytorch_nlp_rest.ipynb		  tfidfmodel.pickle
pytorch_serverless_main_w_exc.py  tf_nlp_rest.ipynb
README.md			  tfserverless_main_w_exc.py
Restaurant_Reviews.tsv.txt	  twitter_sentiment_analysis.ipynb
sc.pickle			  twitter_sentiment_analysis_output_log.txt
storepurchasedata.csv		  use_model_colab.ipynb
storepurchasedata_large.csv	  use_pytorch_dictionary.ipynb
text_classifier.ipynb		  use_tf_model_serving.ipynb


In [ ]:
%cd _05_25_pytorch_create_save_onnx

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

import pandas as pd
import numpy as np

In [ ]:
dataset = pd.read_csv('../_05_20_save_export_reload_pytorch_models/storepurchasedata_large.csv')

In [ ]:
dataset.describe()

Age        Salary    Purchased
count  1554.000000   1554.000000  1554.000000
mean     44.296010  57042.471042     0.694981
std      17.462458  21209.244800     0.460564
min      18.000000  20000.000000     0.000000
25%      27.000000  46000.000000     0.000000
50%      43.000000  60000.000000     1.000000
75%      62.000000  66000.000000     1.000000
max      69.000000  96000.000000     1.000000

In [ ]:
dataset.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   60000          1

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
Xtrain_ = torch.from_numpy(X_train).float()
Xtest_ = torch.from_numpy(X_test).float()

In [ ]:
Xtrain_

tensor([[-0.0935,  0.2215],
        [ 1.2217, -0.5342],
        [-1.0655,  0.4104],
        ...,
        [ 1.2789,  0.4104],
        [-0.9512,  0.2215],
        [-1.2943, -1.4316]])

In [ ]:
ytrain_ = torch.from_numpy(y_train)
ytest_ = torch.from_numpy(y_test)

In [ ]:
ytrain_

tensor([1, 1, 1,  ..., 1, 1, 0])

In [ ]:
Xtrain_.shape, ytrain_.shape

(torch.Size([1243, 2]), torch.Size([1243]))

In [ ]:
Xtest_.shape, ytest_.shape

(torch.Size([311, 2]), torch.Size([311]))

In [ ]:
input_size=2
output_size=2
hidden_size=10

In [ ]:
class Net(nn.Module):
   def __init__(self):
       super(Net, self).__init__()
       self.fc1 = torch.nn.Linear(input_size, hidden_size)
       self.fc2 = torch.nn.Linear(hidden_size, hidden_size)
       self.fc3 = torch.nn.Linear(hidden_size, output_size)


   def forward(self, X):
       X = torch.relu((self.fc1(X)))
       X = torch.relu((self.fc2(X)))
       X = self.fc3(X)

       return F.log_softmax(X,dim=1)

In [ ]:
model = Net()



In [ ]:
import torch.optim as optim
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.NLLLoss()

In [ ]:
epochs = 100


In [ ]:
for epoch in range(epochs):
  optimizer.zero_grad()
  Ypred = model(Xtrain_)
  loss = loss_fn(Ypred,  ytrain_)
  loss.backward()
  optimizer.step()
  print('Epoch',epoch, 'loss',loss.item())

Epoch 0 loss 0.6708754301071167
Epoch 1 loss 0.6480028033256531
Epoch 2 loss 0.6244633197784424
Epoch 3 loss 0.5998685956001282
Epoch 4 loss 0.5757749080657959
Epoch 5 loss 0.5514892935752869
Epoch 6 loss 0.5282143950462341
Epoch 7 loss 0.5055572986602783
Epoch 8 loss 0.48292335867881775
Epoch 9 loss 0.4607465863227844
Epoch 10 loss 0.4394065737724304
Epoch 11 loss 0.4188118577003479
Epoch 12 loss 0.39901837706565857
Epoch 13 loss 0.38010990619659424
Epoch 14 loss 0.3623659014701843
Epoch 15 loss 0.3456202745437622
Epoch 16 loss 0.3299119770526886
Epoch 17 loss 0.31519147753715515
Epoch 18 loss 0.3013388514518738
Epoch 19 loss 0.2883109152317047
Epoch 20 loss 0.27608591318130493
Epoch 21 loss 0.2646941840648651
Epoch 22 loss 0.2539864480495453
Epoch 23 loss 0.24393124878406525
Epoch 24 loss 0.2345324009656906
Epoch 25 loss 0.22566309571266174
Epoch 26 loss 0.21727442741394043
Epoch 27 loss 0.20946916937828064
Epoch 28 loss 0.20211687684059143
Epoch 29 loss 0.1951492726802826
Epoch 30 l

In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.3247, -1.1075],
         [ 1.0102,  0.2048],
         [-0.3630,  0.0785],
         [-0.0777, -0.9317],
         [ 1.0523,  1.2019],
         [ 1.4336,  0.5136],
         [ 0.1913,  0.0030],
         [ 1.0199, -0.2491],
         [-0.6622, -1.2081],
         [-0.3808, -0.8423]], requires_grad=True), Parameter containing:
 tensor([-0.1942,  0.2714,  0.5275,  0.3111,  0.6580,  0.5033, -0.5536,  0.0152,
         -0.1614,  0.3899], requires_grad=True), Parameter containing:
 tensor([[ 0.6279, -1.2938,  0.0645,  0.3994, -0.7839, -0.8910, -0.2796, -0.7575,
           0.7484,  0.6230],
         [ 0.1342,  0.0197, -0.1094, -0.3331, -0.2057,  0.0121,  0.2123, -0.0376,
          -0.2530,  0.1822],
         [-0.2594,  0.4008,  0.2145, -0.0381,  0.0295,  0.2707, -0.1627,  1.1316,
          -0.1745, -0.1265],
         [-0.4639,  0.0311,  0.6726, -0.0324,  0.4087,  0.3157,  0.0175,  0.8055,
          -0.2184, -0.0343],
         [-0.2501,  0.6471,  0.0190, -0.2752,  

In [ ]:
torch.from_numpy(sc.transform(np.array([[40,20000]]))).float()

tensor([[-0.2650, -1.7622]])

In [ ]:
y_cust_20_40000 = model(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_20_40000

tensor([[-1.8368e-03, -6.3006e+00]], grad_fn=<LogSoftmaxBackward0>)

In [ ]:
_, predicted_20_40000 = torch.max(y_cust_20_40000.data,-1)
predicted_20_40000

tensor([0])

In [ ]:
y_cust_42_50000 = model(torch.from_numpy(sc.transform(np.array([[42,50000]]))).float())
y_cust_42_50000

tensor([[-1.1048, -0.4024]], grad_fn=<LogSoftmaxBackward0>)

In [ ]:
_, predicted_42_50000 = torch.max(y_cust_42_50000.data,-1)
predicted_42_50000

tensor([1])

Export model to ONNX format

In [ ]:
sample_tensor = torch.from_numpy(sc.transform(np.array([[40,20000]]))).float()


In [ ]:
torch.onnx.export(model,sample_tensor,"customer.onnx",export_params=True)


In [ ]:
!ls

classifier.pickle		  text_classifier_model
colab_rest_api_pyngrok.ipynb	  text_classifier_model.zip
customer_behavior_model		  textclassifier.pickle
customer_buy.pt			  text_classifier_pytorch
customer_buy_state_dict		  text_classifier_pytorch_1
customer_buy_state_dict.zip	  text_classifier_pytorch_101.ipynb
customermodel.zip		  text_classifier_pytorch.ipynb
customer.onnx			  text_classifier_tensorflow.ipynb
ml_pipeline.ipynb		  tf_customer_buy.ipynb
pytorch_create_save_onnx.ipynb	  tfidfmodel.pickle
pytorch_nlp_rest.ipynb		  tf_nlp_rest.ipynb
pytorch_serverless_main_w_exc.py  tfserverless_main_w_exc.py
README.md			  twitter_sentiment_analysis.ipynb
Restaurant_Reviews.tsv.txt	  twitter_sentiment_analysis_output_log.txt
sc.pickle			  use_model_colab.ipynb
storepurchasedata.csv		  use_pytorch_dictionary.ipynb
storepurchasedata_large.csv	  use_tf_model_serving.ipynb
text_classifier.ipynb


Load the model to TensorFlow

In [ ]:
!pip install onnx


     |████████████████████████████████| 12.8 MB 4.9 MB/s 


In [ ]:
!pip install onnx_tf


     |████████████████████████████████| 226 kB 5.0 MB/s 
     |████████████████████████████████| 1.1 MB 28.6 MB/s 


In [ ]:
import onnx
import onnx_tf


In [ ]:
import tensorflow_addons

In [ ]:
from onnx_tf.backend import prepare


In [ ]:
onnx_model = onnx.load("customer.onnx")


In [ ]:
tf_rep = prepare(onnx_model)


In [ ]:
prediction = tf_rep.run((sc.transform(np.array([[42,50000]],np.float32))))


In [ ]:
prediction

Outputs(_0=array([[-1.1048083 , -0.40238142]], dtype=float32))

In [ ]:
%cd ..

'/content/drive/MyDrive/Github/ml_dl_tweets_sentiment'

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   pytorch_create_save_onnx.ipynb
	modified:   use_tf_model_serving.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	customer.onnx

no changes added to commit (use "git add" and/or "git commit -a")


In [ ]:
# Add local Drive files to GitHub
!git add .

In [ ]:
# Add comment and send added files to GitHub
!git commit -m "Modified files"

[main 2a7c02c] Modified files
 3 files changed, 2 insertions(+), 2 deletions(-)
 create mode 100644 customer.onnx
 rewrite pytorch_create_save_onnx.ipynb (98%)
 rewrite use_tf_model_serving.ipynb (83%)


In [ ]:
# Send to main
!git push

Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 12.32 KiB | 1.76 MiB/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/Putilova/ml_dl_tweets_sentiment.git
   ab2ab8d..2a7c02c  main -> main


In [ ]:
# On git push failure:
git_token = 'token'
username = 'Putilova'
repository = 'ml_dl_tweets_sentiment'
!git remote set-url origin https://{username}:{git_token}@github.com/{username}/{repository}.git