In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%pwd

'/content'

In [ ]:
%cd drive/MyDrive/Github/ml_dl_tweets_sentiment

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment


In [ ]:
!git config --global user.email "email@gmail.com" 
!git config --global user.name "Putilova"

In [ ]:
# When GitHub files aren't in local Drive
!git pull

Already up to date.


In [ ]:
!ls

classifier.pickle	    textclassifier.pickle
README.md		    text_classifier_pytorch
Restaurant_Reviews.tsv.txt  text_classifier_pytorch.ipynb
sc.pickle		    tfidfmodel.pickle
storepurchasedata.csv	    twitter_sentiment_analysis.ipynb
text_classifier.ipynb	    twitter_sentiment_analysis_output_log.txt


In [ ]:
%cd _06_31_text_classifier_pytorch

In [ ]:
import nltk

In [ ]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Pac

True

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('../_06_28_text_classifier/Restaurant_Reviews.tsv.txt', delimiter= '\t', quoting = 3)

In [ ]:
dataset.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [ ]:
from nltk.corpus import stopwords


In [ ]:
from nltk.stem.porter import PorterStemmer


In [ ]:
ps = PorterStemmer()


In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Review  1000 non-null   object
 1   Liked   1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [ ]:
corpus = []


In [ ]:
import re

In [ ]:
for i in range(0, 1000):

  customer_review = re.sub('[^a-zA-Z]', ' ',dataset['Review'][i])
  customer_review = customer_review.lower()
  customer_review = customer_review.split()
  clean_review = [ps.stem(word) for word in customer_review if not word in set(stopwords.words('english'))]
  clean_review = ' '.join(clean_review)
  corpus.append(clean_review)

In [ ]:
corpus[0]

'wow love place'

In [ ]:
corpus[6]

'honeslti tast fresh'

In [ ]:
corpus[12]

'cashier care ever say still end wayyy overpr'

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features = 1500, min_df = 3, max_df = 0.6)


In [ ]:
X = vectorizer.fit_transform(corpus).toarray()


In [ ]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [ ]:
y = dataset.iloc[:, 1].values

In [ ]:
y

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [ ]:
Xtrain_ = torch.from_numpy(X_train).float()
Xtest_ = torch.from_numpy(X_test).float()

In [ ]:
ytrain_ = torch.from_numpy(y_train)
ytest_ = torch.from_numpy(y_test)

In [ ]:
Xtrain_.shape, ytrain_.shape

(torch.Size([800, 467]), torch.Size([800]))

In [ ]:
Xtest_.shape, ytest_.shape

(torch.Size([200, 467]), torch.Size([200]))

In [ ]:
input_size=467
output_size=2
hidden_size=500

In [ ]:
class Net(nn.Module):
   def __init__(self):
       super(Net, self).__init__()
       self.fc1 = torch.nn.Linear(input_size, hidden_size)
       self.fc2 = torch.nn.Linear(hidden_size, hidden_size)
       self.fc3 = torch.nn.Linear(hidden_size, output_size)


   def forward(self, X):
       X = torch.relu((self.fc1(X)))
       X = torch.relu((self.fc2(X)))
       X = self.fc3(X)

       return F.log_softmax(X,dim=1)

In [ ]:
model = Net()


In [ ]:
import torch.optim as optim
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.NLLLoss()

In [ ]:
epochs = 100


In [ ]:
for epoch in range(epochs):
  optimizer.zero_grad()
  Ypred = model(Xtrain_)
  loss = loss_fn(Ypred,  ytrain_)
  loss.backward()
  optimizer.step()
  print('Epoch',epoch, 'loss',loss.item())

Epoch 0 loss 0.6932504177093506
Epoch 1 loss 0.670777440071106
Epoch 2 loss 0.5348039269447327
Epoch 3 loss 0.35636767745018005
Epoch 4 loss 0.21107271313667297
Epoch 5 loss 0.14848196506500244
Epoch 6 loss 0.10014061629772186
Epoch 7 loss 0.07660643756389618
Epoch 8 loss 0.0656379908323288
Epoch 9 loss 0.047642163932323456
Epoch 10 loss 0.0455462820827961
Epoch 11 loss 0.04492887109518051
Epoch 12 loss 0.035660721361637115
Epoch 13 loss 0.03356620669364929
Epoch 14 loss 0.036605119705200195
Epoch 15 loss 0.033503562211990356
Epoch 16 loss 0.029491938650608063
Epoch 17 loss 0.03490278869867325
Epoch 18 loss 0.03113274648785591
Epoch 19 loss 0.029937470331788063
Epoch 20 loss 0.0329180471599102
Epoch 21 loss 0.02907952480018139
Epoch 22 loss 0.030664289370179176
Epoch 23 loss 0.03092207945883274
Epoch 24 loss 0.028763582929968834
Epoch 25 loss 0.030209526419639587
Epoch 26 loss 0.029954390600323677
Epoch 27 loss 0.028628598898649216
Epoch 28 loss 0.02960417978465557
Epoch 29 loss 0.0288

In [ ]:
sample = ["Good batting by England"]


In [ ]:
sample = vectorizer.transform(sample).toarray()


In [ ]:
sample

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [ ]:
torch.from_numpy(sample).float()

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0.,

In [ ]:
sentiment = model(torch.from_numpy(sample).float())
sentiment

tensor([[-1.3815, -0.2893]], grad_fn=<LogSoftmaxBackward0>)

In [ ]:
sample2 = ["bad performance by India in the match"]


In [ ]:
sample2 = vectorizer.transform(sample2).toarray()


In [ ]:
sentiment2 = model(torch.from_numpy(sample2).float())
sentiment2

tensor([[  0.0000, -54.3883]], grad_fn=<LogSoftmaxBackward0>)

In [ ]:
model.state_dict()

OrderedDict([('fc1.weight',
              tensor([[ 0.0685,  0.0301, -0.0293,  ...,  0.0150,  0.0297,  0.0523],
                      [-0.0247,  0.0665, -0.0070,  ...,  0.0361, -0.0818,  0.0680],
                      [ 0.0062, -0.0088,  0.0157,  ..., -0.0090,  0.0170, -0.0415],
                      ...,
                      [-0.1251,  0.0184,  0.0851,  ...,  0.0808,  0.1267, -0.1031],
                      [-0.0389, -0.0254,  0.0057,  ..., -0.0396, -0.0119, -0.0255],
                      [ 0.0765,  0.0246,  0.1138,  ..., -0.0357, -0.0437, -0.0240]])),
             ('fc1.bias',
              tensor([-2.5391e-02, -1.9059e-02, -1.1009e-01,  2.5844e-03,  3.6479e-02,
                      -6.0820e-02, -1.1513e-01, -4.4414e-02, -9.3948e-02, -1.3140e-01,
                       4.4422e-03,  5.8660e-03,  6.2019e-03, -3.2555e-05,  9.3225e-03,
                      -4.2950e-02, -2.6729e-03, -5.9256e-03, -4.9466e-02, -1.0325e-02,
                      -9.0791e-02, -5.7947e-02,  1.5804e-02,  1.

In [ ]:
torch.save(model.state_dict(),'text_classifier_pytorch')

In [ ]:
#from google.colab import files

In [ ]:
#files.download('text_classifier_pytorch')

In [ ]:
import pickle

In [ ]:
with open('tfidfmodel.pickle','wb') as file:
    pickle.dump(vectorizer,file)

In [ ]:
#files.download('tfidfmodel.pickle')

In [ ]:
!ls

classifier.pickle	    textclassifier.pickle
README.md		    text_classifier_pytorch
Restaurant_Reviews.tsv.txt  text_classifier_pytorch.ipynb
sc.pickle		    tfidfmodel.pickle
storepurchasedata.csv	    twitter_sentiment_analysis.ipynb
text_classifier.ipynb	    twitter_sentiment_analysis_output_log.txt


In [ ]:
%cd ..

'/content/drive/MyDrive/Github/ml_dl_tweets_sentiment'

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   text_classifier_pytorch
	new file:   text_classifier_pytorch.ipynb
	modified:   tfidfmodel.pickle
	modified:   twitter_sentiment_analysis.ipynb

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   text_classifier_pytorch
	modified:   text_classifier_pytorch.ipynb
	modified:   tfidfmodel.pickle



In [ ]:
# Add local Drive files to GitHub
!git add .

In [ ]:
# Add comment and send added files to GitHub
!git commit -m "Modified files for PyTorch classifier"

[main ddb8324] Modified files for PyTorch classifier
 4 files changed, 2 insertions(+), 1 deletion(-)
 create mode 100644 text_classifier_pytorch
 create mode 100644 text_classifier_pytorch.ipynb


In [ ]:
# Send to main
!git push

Counting objects: 6, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 1.73 MiB | 5.63 MiB/s, done.
Total 6 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/Putilova/ml_dl_tweets_sentiment
   af624e4..ddb8324  main -> main
