In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%pwd

'/content'

In [ ]:
%cd drive/MyDrive/Github/ml_dl_tweets_sentiment

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment


In [ ]:
%cd  _07_43_tfjs4

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment/_07_43_tfjs4


In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
#dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/storepurchasedata_large.csv')
dataset = pd.read_csv('../_05_20_save_export_reload_pytorch_models/storepurchasedata_large.csv')

In [ ]:
dataset.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   60000          1

In [ ]:
dataset.describe()

Age        Salary    Purchased
count  1554.000000   1554.000000  1554.000000
mean     44.296010  57042.471042     0.694981
std      17.462458  21209.244800     0.460564
min      18.000000  20000.000000     0.000000
25%      27.000000  46000.000000     0.000000
50%      43.000000  60000.000000     1.000000
75%      62.000000  66000.000000     1.000000
max      69.000000  96000.000000     1.000000

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(2, activation='softmax')
])

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=50)


Epoch 1/50
39/39 [==============================] - 1s 2ms/step - loss: 0.7178 - accuracy: 0.5591
Epoch 2/50
39/39 [==============================] - 0s 2ms/step - loss: 0.5825 - accuracy: 0.8286
Epoch 3/50
39/39 [==============================] - 0s 2ms/step - loss: 0.4692 - accuracy: 0.9437
Epoch 4/50
39/39 [==============================] - 0s 2ms/step - loss: 0.3704 - accuracy: 0.9501
Epoch 5/50
39/39 [==============================] - 0s 2ms/step - loss: 0.2911 - accuracy: 0.9477
Epoch 6/50
39/39 [==============================] - 0s 2ms/step - loss: 0.2320 - accuracy: 0.9453
Epoch 7/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1899 - accuracy: 0.9533
Epoch 8/50
39/39 [==============================] - 0s 3ms/step - loss: 0.1626 - accuracy: 0.9525
Epoch 9/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1457 - accuracy: 0.9541
Epoch 10/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1358 - accuracy: 0.9566
Epoch 11/50
39/39 [

In [ ]:
loss, accuracy =model.evaluate(X_test, y_test)


10/10 [==============================] - 0s 2ms/step - loss: 0.1174 - accuracy: 0.9550


In [ ]:
loss

0.11740833520889282

In [ ]:
accuracy

0.9549839496612549

In [ ]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 2)                 22        
                                                                 
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [ ]:
prediction1 = model.predict(sc.transform(np.array([[42,50000]])))[:,1]
prediction1

array([0.6086768], dtype=float32)

In [ ]:
predict2 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict2

array([0.0053079], dtype=float32)

In [ ]:
model.save('customer_behavior_model/1')


INFO:tensorflow:Assets written to: customer_behavior_model/1/assets


In [ ]:
!ls

customer_behavior_model  group1-shard1of1.bin  tf3_keras_age_salary_tfjs.ipynb
customermodel.zip	 model.json	       tfjsdemo.html


In [ ]:
!ls customer_behavior_model/1

assets	keras_metadata.pb  saved_model.pb  variables


In [ ]:
from tensorflow.keras.models import load_model


In [ ]:
cust_model = load_model('customer_behavior_model/1/')

In [ ]:
prediction3 = cust_model.predict(sc.transform(np.array([[42,50000]])))[:,1]
prediction3

array([0.6086768], dtype=float32)

In [ ]:
predict4 = cust_model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict4

array([0.0053079], dtype=float32)

In [ ]:
sc.transform(np.array([[20,40000]]))

array([[-1.40863043, -0.81755432]])

In [ ]:
sc.transform(np.array([[42,50000]]))

array([[-0.15065689, -0.34524533]])

In [ ]:
!ls

customer_behavior_model  group1-shard1of1.bin		  tfjsdemo.html
customermodel.zip	 tf3_keras_age_salary_tfjs.ipynb


In [ ]:
!zip -r customermodel.zip customer_behavior_model  

updating: customer_behavior_model/ (stored 0%)
updating: customer_behavior_model/1/ (stored 0%)
updating: customer_behavior_model/1/variables/ (stored 0%)
updating: customer_behavior_model/1/variables/variables.data-00000-of-00001 (deflated 58%)
updating: customer_behavior_model/1/variables/variables.index (deflated 64%)
updating: customer_behavior_model/1/assets/ (stored 0%)
updating: customer_behavior_model/1/saved_model.pb (deflated 88%)
updating: customer_behavior_model/1/keras_metadata.pb (deflated 86%)


In [ ]:
!ls


customer_behavior_model  group1-shard1of1.bin  tf3_keras_age_salary_tfjs.ipynb
customermodel.zip	 model.json	       tfjsdemo.html


In [ ]:
from google.colab import files


In [ ]:
!pip install tensorflowjs

     |████████████████████████████████| 77 kB 3.6 MB/s 
     |████████████████████████████████| 462 kB 19.5 MB/s 


In [ ]:
import tensorflowjs as tfjs

In [ ]:
tfjs.__version__

'3.14.0'

In [ ]:
tfjs.converters.save_keras_model(model, "/")

In [ ]:
!ls

customer_behavior_model  group1-shard1of1.bin  tf3_keras_age_salary_tfjs.ipynb
customermodel.zip	 model.json	       tfjsdemo.html


In [ ]:
!cat model.json

cat: model.json: No such file or directory


In [ ]:
#from google.colab import files


In [ ]:
#files.download('model.json')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
#files.download('group1-shard1of1.bin')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>