In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
%pwd

'/content'

In [4]:
%cd drive/MyDrive/Github/ml_dl_tweets_sentiment

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment


In [39]:
!git config --global user.email "email@gmail.com" 
!git config --global user.name "Putilova"

In [48]:
# When GitHub files aren't in local Drive
!git pull

error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.


In [5]:
%cd  _07_43_tfjs4

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment/_07_43_tfjs4


In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [6]:
#dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/storepurchasedata_large.csv')
dataset = pd.read_csv('../_05_20_save_export_reload_pytorch_models/storepurchasedata_large.csv')

In [7]:
dataset.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   60000          1

In [8]:
dataset.describe()

Age        Salary    Purchased
count  1554.000000   1554.000000  1554.000000
mean     44.296010  57042.471042     0.694981
std      17.462458  21209.244800     0.460564
min      18.000000  20000.000000     0.000000
25%      27.000000  46000.000000     0.000000
50%      43.000000  60000.000000     1.000000
75%      62.000000  66000.000000     1.000000
max      69.000000  96000.000000     1.000000

In [9]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(2, activation='softmax')
])

In [13]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [14]:
model.fit(X_train, y_train, epochs=50)


Epoch 1/50
39/39 [==============================] - 1s 2ms/step - loss: 0.6107 - accuracy: 0.6846
Epoch 2/50
39/39 [==============================] - 0s 2ms/step - loss: 0.5177 - accuracy: 0.6991
Epoch 3/50
39/39 [==============================] - 0s 2ms/step - loss: 0.4472 - accuracy: 0.6991
Epoch 4/50
39/39 [==============================] - 0s 2ms/step - loss: 0.3951 - accuracy: 0.6991
Epoch 5/50
39/39 [==============================] - 0s 2ms/step - loss: 0.3577 - accuracy: 0.6991
Epoch 6/50
39/39 [==============================] - 0s 2ms/step - loss: 0.3259 - accuracy: 0.6991
Epoch 7/50
39/39 [==============================] - 0s 2ms/step - loss: 0.3024 - accuracy: 0.9059
Epoch 8/50
39/39 [==============================] - 0s 2ms/step - loss: 0.2842 - accuracy: 0.9445
Epoch 9/50
39/39 [==============================] - 0s 2ms/step - loss: 0.2692 - accuracy: 0.9461
Epoch 10/50
39/39 [==============================] - 0s 2ms/step - loss: 0.2570 - accuracy: 0.9445
Epoch 11/50
39/39 [

In [15]:
loss, accuracy =model.evaluate(X_test, y_test)


10/10 [==============================] - 0s 2ms/step - loss: 0.1145 - accuracy: 0.9550


In [16]:
loss

0.11448760330677032

In [17]:
accuracy

0.9549839496612549

In [18]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 2)                 22        
                                                                 
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [19]:
prediction1 = model.predict(sc.transform(np.array([[42,50000]])))[:,1]
prediction1

array([0.750801], dtype=float32)

In [20]:
predict2 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict2

array([0.1091934], dtype=float32)

In [21]:
model.save('customer_behavior_model/1')


INFO:tensorflow:Assets written to: customer_behavior_model/1/assets


In [22]:
!ls

customer_behavior_model  tf3_keras_age_salary_tfjs.ipynb
group1-shard1of1.bin	 tf3_keras_age_salary_tfjs.py
model.json		 tfjsdemo.html


In [23]:
!ls customer_behavior_model/1

assets	keras_metadata.pb  saved_model.pb  variables


In [24]:
from tensorflow.keras.models import load_model


In [25]:
cust_model = load_model('customer_behavior_model/1/')

In [26]:
prediction3 = cust_model.predict(sc.transform(np.array([[42,50000]])))[:,1]
prediction3

array([0.750801], dtype=float32)

In [27]:
predict4 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict4

array([0.1091934], dtype=float32)

In [28]:
sc.transform(np.array([[20,40000]]))

array([[-1.40863043, -0.81755432]])

In [29]:
sc.transform(np.array([[42,50000]]))

array([[-0.15065689, -0.34524533]])

In [30]:
!ls

customer_behavior_model  tf3_keras_age_salary_tfjs.ipynb
group1-shard1of1.bin	 tf3_keras_age_salary_tfjs.py
model.json		 tfjsdemo.html


In [31]:
!zip -r customermodel.zip customer_behavior_model  

  adding: customer_behavior_model/ (stored 0%)
  adding: customer_behavior_model/1/ (stored 0%)
  adding: customer_behavior_model/1/variables/ (stored 0%)
  adding: customer_behavior_model/1/variables/variables.data-00000-of-00001 (deflated 59%)
  adding: customer_behavior_model/1/variables/variables.index (deflated 64%)
  adding: customer_behavior_model/1/assets/ (stored 0%)
  adding: customer_behavior_model/1/saved_model.pb (deflated 88%)
  adding: customer_behavior_model/1/keras_metadata.pb (deflated 86%)


In [32]:
!ls


customer_behavior_model  model.json			  tfjsdemo.html
customermodel.zip	 tf3_keras_age_salary_tfjs.ipynb
group1-shard1of1.bin	 tf3_keras_age_salary_tfjs.py


In [33]:
from google.colab import files


In [34]:
!pip install tensorflowjs

     |████████████████████████████████| 77 kB 2.8 MB/s 
     |████████████████████████████████| 462 kB 11.2 MB/s 


In [35]:
import tensorflowjs as tfjs


In [36]:
tfjs.converters.save_keras_model(model, "/content/")

In [37]:
!ls

customer_behavior_model  model.json			  tfjsdemo.html
customermodel.zip	 tf3_keras_age_salary_tfjs.ipynb
group1-shard1of1.bin	 tf3_keras_age_salary_tfjs.py


In [38]:
!cat model.json

{"format": "layers-model", "generatedBy": "keras v2.4.0", "convertedBy": "TensorFlow.js Converter v2.7.0", "modelTopology": {"keras_version": "2.4.0", "backend": "tensorflow", "model_config": {"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 2], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_input"}}, {"class_name": "Dense", "config": {"name": "dense", "trainable": true, "dtype": "float32", "units": 10, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 10, "activation": "relu", "use_bias": true, "kernel_initiali

In [ ]:
#from google.colab import files


In [ ]:
#files.download('model.json')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
#files.download('group1-shard1of1.bin')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [41]:
%cd ..

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment


In [43]:
!git status

On branch main
Your branch is behind 'origin/main' by 4 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   README.md
	modified:   _05_24_tf_model_serving/_05_24_GCP_VM.txt
	modified:   drive-collab-github.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	_07_41_tfjs1/
	_07_42_tfjs2/
	_07_43_tfjs4/
	_08_44_linear_regression/
	_08_45_model_as_code/
	_09_46_models_in_db/
	_09_47_local_model_store/
	_10_50_ml_pipeline_mlfow/
	_10_51_running_mlflow_on_colab/
	_10_52_mlflow_pytorch/
	_10_54_mlflow-deploy/

no changes added to commit (use "git add" and/or "git commit -a")


In [49]:
# Add local Drive files to GitHub
!git add .

In [50]:
# Add comment and send added files to GitHub
!git commit -m "Updated"

[main e61cf26] Updated


In [51]:
# Send to main
!git push

Counting objects: 52, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (48/48), done.
Writing objects: 100% (52/52), 53.58 KiB | 1.09 MiB/s, done.
Total 52 (delta 12), reused 0 (delta 0)
remote: Resolving deltas: 100% (12/12), completed with 4 local objects.
To https://github.com/Putilova/ml_dl_tweets_sentiment.git
   900ae25..e61cf26  main -> main


In [ ]:
git_token = 'token'
username = 'Putilova'
repository = 'ml_dl_tweets_sentiment'

In [ ]:
!git remote set-url origin https://{username}:{git_token}@github.com/{username}/{repository}.git