In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%pwd

'/content'

In [ ]:
%cd drive/MyDrive/Github/ml_dl_tweets_sentiment

/content/drive/MyDrive/Github/ml_dl_tweets_sentiment


In [ ]:
%cd _05_20_save_export_reload_pytorch_models

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

import pandas as pd
import numpy as np

In [ ]:
dataset = pd.read_csv('storepurchasedata_large.csv')

In [ ]:
dataset.describe()

Age        Salary    Purchased
count  1554.000000   1554.000000  1554.000000
mean     44.296010  57042.471042     0.694981
std      17.462458  21209.244800     0.460564
min      18.000000  20000.000000     0.000000
25%      27.000000  46000.000000     0.000000
50%      43.000000  60000.000000     1.000000
75%      62.000000  66000.000000     1.000000
max      69.000000  96000.000000     1.000000

In [ ]:
dataset.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   60000          1

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
Xtrain_ = torch.from_numpy(X_train).float()
Xtest_ = torch.from_numpy(X_test).float()

In [ ]:
Xtrain_

tensor([[-0.0935,  0.2215],
        [ 1.2217, -0.5342],
        [-1.0655,  0.4104],
        ...,
        [ 1.2789,  0.4104],
        [-0.9512,  0.2215],
        [-1.2943, -1.4316]])

In [ ]:
ytrain_ = torch.from_numpy(y_train)
ytest_ = torch.from_numpy(y_test)

In [ ]:
ytrain_

tensor([1, 1, 1,  ..., 1, 1, 0])

In [ ]:
Xtrain_.shape, ytrain_.shape

(torch.Size([1243, 2]), torch.Size([1243]))

In [ ]:
Xtest_.shape, ytest_.shape

(torch.Size([311, 2]), torch.Size([311]))

In [ ]:
input_size=2
output_size=2
hidden_size=10

In [ ]:
class Net(nn.Module):
   def __init__(self):
       super(Net, self).__init__()
       self.fc1 = torch.nn.Linear(input_size, hidden_size)
       self.fc2 = torch.nn.Linear(hidden_size, hidden_size)
       self.fc3 = torch.nn.Linear(hidden_size, output_size)


   def forward(self, X):
       X = torch.relu((self.fc1(X)))
       X = torch.relu((self.fc2(X)))
       X = self.fc3(X)

       return F.log_softmax(X,dim=1)

In [ ]:
model = Net()



In [ ]:
import torch.optim as optim
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.NLLLoss()

In [ ]:
epochs = 100


In [ ]:
for epoch in range(epochs):
  optimizer.zero_grad()
  Ypred = model(Xtrain_)
  loss = loss_fn(Ypred,  ytrain_)
  loss.backward()
  optimizer.step()
  print('Epoch',epoch, 'loss',loss.item())

Epoch 0 loss 0.7431748509407043
Epoch 1 loss 0.71706622838974
Epoch 2 loss 0.6956674456596375
Epoch 3 loss 0.6788403987884521
Epoch 4 loss 0.6655853986740112
Epoch 5 loss 0.6551051139831543
Epoch 6 loss 0.6467150449752808
Epoch 7 loss 0.6398341059684753
Epoch 8 loss 0.6337618231773376
Epoch 9 loss 0.6278884410858154
Epoch 10 loss 0.6219142079353333
Epoch 11 loss 0.6156854629516602
Epoch 12 loss 0.6092445254325867
Epoch 13 loss 0.6025052070617676
Epoch 14 loss 0.5953503251075745
Epoch 15 loss 0.5877799391746521
Epoch 16 loss 0.5798270106315613
Epoch 17 loss 0.5716344118118286
Epoch 18 loss 0.5631721615791321
Epoch 19 loss 0.5544381737709045
Epoch 20 loss 0.545444667339325
Epoch 21 loss 0.5363165140151978
Epoch 22 loss 0.5270870923995972
Epoch 23 loss 0.5179008841514587
Epoch 24 loss 0.5088701844215393
Epoch 25 loss 0.5001254081726074
Epoch 26 loss 0.49174273014068604
Epoch 27 loss 0.4835483133792877
Epoch 28 loss 0.4755396842956543
Epoch 29 loss 0.46768125891685486
Epoch 30 loss 0.45990

In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.9846,  0.3750],
         [-0.9117,  0.5620],
         [ 0.6306, -0.3455],
         [-0.9090, -1.1395],
         [-0.4314, -0.5231],
         [-0.9363, -0.2038],
         [ 0.6245,  0.5510],
         [-0.0660, -0.2169],
         [-0.8594,  0.5454],
         [ 0.3609, -0.4367]], requires_grad=True), Parameter containing:
 tensor([ 0.6023,  0.1797,  0.6597,  0.3468,  0.0877,  0.6047,  0.9477, -0.6841,
          0.1658, -0.1921], requires_grad=True), Parameter containing:
 tensor([[-0.3140, -0.2135, -0.0818, -0.2008,  0.0508,  0.1235, -0.2730, -0.2843,
          -0.0052, -0.1313],
         [-0.0662, -0.1291, -0.1981, -0.2941, -0.1077, -0.3990,  0.1983,  0.2723,
           0.0276, -0.0104],
         [ 0.1421, -0.2626, -0.4430, -0.3305,  0.1255, -0.2602, -0.0684,  0.1076,
           0.0341, -0.4398],
         [ 0.0740, -0.1213, -0.0441, -0.0579,  0.0253, -0.1156, -0.1438,  0.2219,
           0.2641, -0.2970],
         [ 0.7111,  0.2840,  0.3896, -0.4999, -

In [ ]:
torch.from_numpy(sc.transform(np.array([[40,20000]]))).float()

tensor([[-0.2650, -1.7622]])

In [ ]:
y_cust_20_40000 = model(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_20_40000

tensor([[-0.3974, -1.1150]], grad_fn=<LogSoftmaxBackward0>)

In [ ]:
_, predicted_20_40000 = torch.max(y_cust_20_40000.data,-1)
predicted_20_40000

tensor([0])

In [ ]:
y_cust_42_50000 = model(torch.from_numpy(sc.transform(np.array([[42,50000]]))).float())
y_cust_42_50000

tensor([[-1.2433, -0.3403]], grad_fn=<LogSoftmaxBackward0>)

In [ ]:
_, predicted_42_50000 = torch.max(y_cust_42_50000.data,-1)
predicted_42_50000

tensor([1])

In [ ]:
torch.save(model,'customer_buy.pt')

In [ ]:
!ls

classifier.pickle		  text_classifier_model.zip
colab_rest_api_pyngrok.ipynb	  textclassifier.pickle
customer_buy.pt			  text_classifier_pytorch
ml_pipeline.ipynb		  text_classifier_pytorch_1
pytorch_nlp_rest.ipynb		  text_classifier_pytorch_101.ipynb
pytorch_serverless_main_w_exc.py  text_classifier_pytorch.ipynb
README.md			  text_classifier_tensorflow.ipynb
Restaurant_Reviews.tsv.txt	  tfidfmodel.pickle
sc.pickle			  tf_nlp_rest.ipynb
storepurchasedata.csv		  tfserverless_main_w_exc.py
storepurchasedata_large.csv	  twitter_sentiment_analysis.ipynb
text_classifier.ipynb		  twitter_sentiment_analysis_output_log.txt
text_classifier_model		  use_model_colab.ipynb


In [ ]:
restored_model = torch.load('customer_buy.pt')

In [ ]:
y_cust_20_40000 = restored_model(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_20_40000

tensor([[-0.3974, -1.1150]], grad_fn=<LogSoftmaxBackward0>)

In [ ]:
_, predicted_20_40000 = torch.max(y_cust_20_40000.data,-1)
predicted_20_40000

tensor([0])

In [ ]:
model.state_dict()

OrderedDict([('fc1.weight', tensor([[ 0.9846,  0.3750],
                      [-0.9117,  0.5620],
                      [ 0.6306, -0.3455],
                      [-0.9090, -1.1395],
                      [-0.4314, -0.5231],
                      [-0.9363, -0.2038],
                      [ 0.6245,  0.5510],
                      [-0.0660, -0.2169],
                      [-0.8594,  0.5454],
                      [ 0.3609, -0.4367]])),
             ('fc1.bias',
              tensor([ 0.6023,  0.1797,  0.6597,  0.3468,  0.0877,  0.6047,  0.9477, -0.6841,
                       0.1658, -0.1921])),
             ('fc2.weight',
              tensor([[-0.3140, -0.2135, -0.0818, -0.2008,  0.0508,  0.1235, -0.2730, -0.2843,
                       -0.0052, -0.1313],
                      [-0.0662, -0.1291, -0.1981, -0.2941, -0.1077, -0.3990,  0.1983,  0.2723,
                        0.0276, -0.0104],
                      [ 0.1421, -0.2626, -0.4430, -0.3305,  0.1255, -0.2602, -0.0684,  0.1076,
   

In [ ]:
torch.save(model.state_dict(),'customer_buy_state_dict')

In [ ]:
!ls

classifier.pickle		  text_classifier_model.zip
colab_rest_api_pyngrok.ipynb	  textclassifier.pickle
customer_buy.pt			  text_classifier_pytorch
customer_buy_state_dict		  text_classifier_pytorch_1
ml_pipeline.ipynb		  text_classifier_pytorch_101.ipynb
pytorch_nlp_rest.ipynb		  text_classifier_pytorch.ipynb
pytorch_serverless_main_w_exc.py  text_classifier_tensorflow.ipynb
README.md			  tfidfmodel.pickle
Restaurant_Reviews.tsv.txt	  tf_nlp_rest.ipynb
sc.pickle			  tfserverless_main_w_exc.py
storepurchasedata.csv		  twitter_sentiment_analysis.ipynb
storepurchasedata_large.csv	  twitter_sentiment_analysis_output_log.txt
text_classifier.ipynb		  use_model_colab.ipynb
text_classifier_model


In [ ]:
new_predictor = Net()

In [ ]:
y_cust_20_40000 = new_predictor(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_20_40000

tensor([[-0.7547, -0.6352]], grad_fn=<LogSoftmaxBackward0>)

In [ ]:
!zip -r customer_buy_state_dict.zip customer_buy_state_dict

  adding: customer_buy_state_dict (deflated 46%)


In [ ]:
!ls

classifier.pickle		  text_classifier_model
colab_rest_api_pyngrok.ipynb	  text_classifier_model.zip
customer_buy.pt			  textclassifier.pickle
customer_buy_state_dict		  text_classifier_pytorch
customer_buy_state_dict.zip	  text_classifier_pytorch_1
ml_pipeline.ipynb		  text_classifier_pytorch_101.ipynb
pytorch_nlp_rest.ipynb		  text_classifier_pytorch.ipynb
pytorch_serverless_main_w_exc.py  text_classifier_tensorflow.ipynb
README.md			  tfidfmodel.pickle
Restaurant_Reviews.tsv.txt	  tf_nlp_rest.ipynb
sc.pickle			  tfserverless_main_w_exc.py
storepurchasedata.csv		  twitter_sentiment_analysis.ipynb
storepurchasedata_large.csv	  twitter_sentiment_analysis_output_log.txt
text_classifier.ipynb		  use_model_colab.ipynb


In [ ]:
from google.colab import files


In [ ]:
#files.download('customer_buy_state_dict.zip')